package dev.hivens.skinema.libav

import java.nio.file.Files
import java.nio.file.Path

/**
 * Builds an H.264 file carrying CEA-608 closed captions, by hand.
 *
 * Every other fixture in this suite is generated by the `ffmpeg` CLI, which is
 * the rule: a committed binary rots and cannot be read. This one cannot follow
 * it, because **FFmpeg has no CEA-608 encoder**. Its subtitle encoders are
 * ass, dvbsub, dvdsub, mov_text, srt, text, ttml, webvtt and xsub -- there is
 * no path from the command line to a file with captions in it, and `-a53cc`
 * on libx264 only passes through captions an input already had.
 *
 * So the generator IS the fixture. It encodes an ordinary picture with x264,
 * then writes the caption bytes into the bitstream itself: captions are not a
 * stream, they ride as SEI inside the video, which is the whole reason this
 * format needs a different path through the library than every other subtitle
 * kind.
 *
 * What it produces is verified against FFmpeg rather than against this code --
 * see `ClosedCaptionFixtureTest`, which reads the result back through the
 * `movie` filter's own caption output. A fixture nobody has independently read
 * is an assertion about the generator, not about the format.
 */
internal object ClosedCaptionFixture {

    /**
     * Writes [name] into [dir]: [seconds] of a solid colour at 25 fps, with
     * [text] captioned from the first frame onward. Returns the file.
     */
    fun generate(dir: Path, name: String, text: String = "HI", seconds: String = "2"): Path {
        val annexB = Fixtures.generate(
            dir.resolve("$name.base.h264"),
            "-f", "lavfi", "-i", "color=c=navy:s=320x240:r=25:d=$seconds",
            "-c:v", "libx264", "-preset", "ultrafast", "-g", "25",
            // Annex-B is the form the caption NALs are written into: length-
            // prefixed AVCC would need every prefix ahead of the insertion
            // rewritten, and the muxer converts back on the way into mp4.
            "-bsf:v", "h264_mp4toannexb", "-f", "h264",
        )
        val injected = dir.resolve("$name.cc.h264")
        Files.write(injected, inject(Files.readAllBytes(annexB), sei(captionPairs(text))))
        return Fixtures.generate(dir.resolve(name), "-f", "h264", "-i", injected.toString(), "-c", "copy")
    }

    /**
     * The caption itself, as CEA-608 byte pairs on field 1, channel 1.
     *
     * Roll-up rather than pop-on, because it is the shortest sequence that
     * displays anything: erase what is shown, enter two-row roll-up, carriage
     * return, then the characters. Each control code is sent TWICE, which is
     * the convention the format is built on -- a decoder treats an immediate
     * repeat as the same command rather than two, so doubling costs nothing
     * and survives a dropped pair.
     */
    private fun captionPairs(text: String): List<Pair<Int, Int>> {
        val pairs = mutableListOf<Pair<Int, Int>>()
        for (control in listOf(0x14 to 0x2C, 0x14 to 0x25, 0x14 to 0x2D)) {
            pairs += control
            pairs += control
        }
        var i = 0
        while (i < text.length) {
            // 0x80 pads an odd tail: it is the null the format uses, not a
            // character, and carries even parity of its own.
            val second = if (i + 1 < text.length) text[i + 1].code else 0x80
            pairs += text[i].code to second
            i += 2
        }
        return pairs
    }

    /**
     * One SEI NAL carrying the pairs as ATSC A53 Part 4 user data.
     *
     * The payload is the registered ITU-T T.35 form the h264 decoder looks
     * for: country code 0xB5, ATSC provider 0x0031, the identifier `GA94`, and
     * user_data_type_code 3 for cc_data. Then a flags byte whose 0x40 bit is
     * process_cc_data_flag -- without it the decoder reads the count and
     * returns -- with the pair count in its low five bits, one byte of em_data,
     * the pairs, and a marker.
     *
     * Each pair goes out as a triplet whose first byte is 0xFC: five marker
     * bits, cc_valid, and a two-bit type where 0 is field 1. The two data bytes
     * carry ODD parity in bit 7, which is what the format checks and what a
     * decoder drops the pair for if it is wrong.
     */
    private fun sei(pairs: List<Pair<Int, Int>>): ByteArray {
        val payload = mutableListOf<Int>()
        payload += listOf(0xB5, 0x00, 0x31)
        "GA94".forEach { payload += it.code }
        payload += 0x03
        payload += 0xC0 or pairs.size
        payload += 0xFF
        for ((a, b) in pairs) payload += listOf(0xFC, oddParity(a), oddParity(b))
        payload += 0xFF

        val nal = mutableListOf(0x06, 0x04)          // nal_unit_type 6 (SEI), payload_type 4
        var remaining = payload.size
        while (remaining >= 255) {
            nal += 0xFF
            remaining -= 255
        }
        nal += remaining
        nal += emulationPrevented(payload)
        nal += 0x80                                   // rbsp_trailing_bits
        return (listOf(0x00, 0x00, 0x00, 0x01) + nal).map { it.toByte() }.toByteArray()
    }

    /** Bit 7 set so the byte carries an odd number of ones. */
    private fun oddParity(value: Int): Int {
        val v = value and 0x7F
        return if (Integer.bitCount(v) % 2 == 1) v else v or 0x80
    }

    /**
     * Inserts 0x03 after any two zero bytes, which is what keeps a payload
     * from spelling a start code. Nothing this generator emits would, since
     * only the provider code carries a zero at all -- it is here because a
     * payload that grows later would, silently and only for some text.
     */
    private fun emulationPrevented(payload: List<Int>): List<Int> {
        val out = mutableListOf<Int>()
        var zeros = 0
        for (b in payload) {
            if (zeros >= 2 && b <= 3) {
                out += 0x03
                zeros = 0
            }
            out += b
            zeros = if (b == 0) zeros + 1 else 0
        }
        return out
    }

    /**
     * Writes [sei] in front of the first few coded pictures.
     *
     * Before the slice rather than anywhere: an SEI belongs to the access unit
     * that follows it, so a caption attached after its picture would be read
     * against the next one. A handful of repeats rather than one, because a
     * roll-up caption is a sequence of commands and a decoder that joined the
     * stream late would otherwise see the characters with no mode set.
     */
    private fun inject(stream: ByteArray, sei: ByteArray, upTo: Int = 4): ByteArray {
        val out = java.io.ByteArrayOutputStream(stream.size + sei.size * upTo)
        var written = 0
        var injected = 0
        var i = 0
        while (i + 3 < stream.size) {
            val isStart = stream[i] == 0.toByte() && stream[i + 1] == 0.toByte() && stream[i + 2] == 1.toByte()
            if (!isStart) {
                i++
                continue
            }
            val type = stream[i + 3].toInt() and 0x1F
            // A four-byte start code is a three-byte one with a zero in front;
            // the SEI has to go before the whole of it, not between.
            val boundary = if (i > 0 && stream[i - 1] == 0.toByte()) i - 1 else i
            if (type == 1 || type == 5) {
                if (injected < upTo) {
                    out.write(stream, written, boundary - written)
                    out.write(sei)
                    written = boundary
                    injected++
                }
            }
            i += 3
        }
        out.write(stream, written, stream.size - written)
        check(injected > 0) { "found no coded picture to attach captions to" }
        return out.toByteArray()
    }
}
